import 'dotenv/config';

/**
 * TalentMatrix AI & Behavioral Telemetry Architecture
 * 
 * Strict separation between:
 * 1. Behavioral Telemetry Scoring Engine: Deterministic feature extraction & mathematical scoring.
 * 2. Generative AI Providers: Google Gemini (gemini-1.5-pro) / OpenAI (gpt-4o) for natural language reasoning.
 * 
 * Never disguises heuristic rules as LLM output.
 */

export interface TelemetrySignalContribution {
  signal: string;
  value: number;
  weight: number;
  riskContribution: number;
  description: string;
}

export interface AnomalyAnalysisRequest {
  studentName: string;
  studentId: string;
  assessmentName: string;
  authenticityScore: number;
  riskLevel: string;
  signals: TelemetrySignalContribution[];
  recentEvents: { eventType: string; timestamp: string; data: any }[];
}

export interface AnomalyAnalysisResponse {
  isAIAvailable: boolean;
  aiProvider: string | null;
  aiModel: string | null;
  timestamp: string;
  generativeExplanation: string | null;
  behavioralRiskBreakdown: {
    authenticityScore: number;
    riskLevel: string;
    contributingFactors: string[];
    technicalHeuristics: string;
    recommendedActions: string[];
  };
}

export interface AllocationExplanationRequest {
  studentName: string;
  studentId: string;
  department: string;
  gpa: number;
  assignedCompany: string;
  assignedRole: string;
  assignedTier: string;
  studentRankForDrive: number;
  totalPositions: number;
  policyApplied?: { name: string; tier: string; rules: any };
}

export interface AllocationExplanationResponse {
  isAIAvailable: boolean;
  aiProvider: string | null;
  aiModel: string | null;
  timestamp: string;
  generativeReasoning: string | null;
  deterministicAllocationSummary: string;
  policyComplianceNotes: string;
}

export interface IAIProvider {
  readonly name: string;
  readonly modelId: string;
  isAvailable(): boolean;
  generateAnomalyReasoning(request: AnomalyAnalysisRequest): Promise<string>;
  generateAllocationReasoning(request: AllocationExplanationRequest): Promise<string>;
}

// ─── 1. Google Gemini Provider ─────────────────────────────────
export class GeminiProvider implements IAIProvider {
  readonly name = 'Google Gemini';
  readonly modelId = process.env.GEMINI_MODEL || 'gemini-1.5-pro';
  private apiKey: string | undefined;

  constructor() {
    this.apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
  }

  isAvailable(): boolean {
    return Boolean(this.apiKey && this.apiKey.trim().length > 0);
  }

  async generateAnomalyReasoning(request: AnomalyAnalysisRequest): Promise<string> {
    if (!this.isAvailable()) {
      throw new Error('GEMINI_API_KEY is not configured in server environment.');
    }

    const significantSignals = request.signals.filter((s) => s.riskContribution > 0);
    const prompt = `You are an assessment integrity auditor for a university placement exam.
Analyze this candidate's exact telemetry data and explain the behavioral risk profile in 2-3 professional sentences.

Candidate: ${request.studentName} (${request.studentId})
Assessment: ${request.assessmentName}
Observed Authenticity Score: ${request.authenticityScore}/100 (${request.riskLevel.toUpperCase()} Risk)

Actual Observed Signals:
${significantSignals.map((s) => `- ${s.signal}: value=${s.value} (${s.description})`).join('\n') || 'None - Standard typing cadence'}

Recent Event Sequence (${request.recentEvents.length} events logged):
${request.recentEvents.slice(0, 10).map((e) => `[${e.timestamp}] ${e.eventType} -> ${JSON.stringify(e.data)}`).join('\n')}

Provide an objective, non-accusatory evaluation of the observed telemetry evidence. State clearly what was observed in the editor.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${this.modelId}:generateContent?key=${this.apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );

    if (!response.ok) {
      throw new Error(`Gemini API returned ${response.status}: ${response.statusText}`);
    }

    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || 'Analysis generated by Gemini.';
  }

  async generateAllocationReasoning(request: AllocationExplanationRequest): Promise<string> {
    if (!this.isAvailable()) {
      throw new Error('GEMINI_API_KEY is not configured.');
    }

    const prompt = `Explain why student ${request.studentName} (GPA: ${request.gpa.toFixed(2)}, Dept: ${request.department}) received an offer from ${request.assignedCompany} for ${request.assignedRole} (${request.assignedTier.toUpperCase()} tier).
Candidate was ranked #${request.studentRankForDrive} out of ${request.totalPositions} positions available.
Offer Policy: ${JSON.stringify(request.policyApplied || {})}.
Write a concise, professional explanation for the T&P committee.`;

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${this.modelId}:generateContent?key=${this.apiKey}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
        }),
      }
    );

    if (!response.ok) throw new Error(`Gemini API returned ${response.status}`);
    const data = await response.json();
    return data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() || 'Allocation verified by Gemini.';
  }
}

// ─── 2. OpenAI Provider ────────────────────────────────────────
export class OpenAIProvider implements IAIProvider {
  readonly name = 'OpenAI';
  readonly modelId = process.env.OPENAI_MODEL || 'gpt-4o';
  private apiKey: string | undefined;

  constructor() {
    this.apiKey = process.env.OPENAI_API_KEY;
  }

  isAvailable(): boolean {
    return Boolean(this.apiKey && this.apiKey.trim().length > 0);
  }

  async generateAnomalyReasoning(request: AnomalyAnalysisRequest): Promise<string> {
    if (!this.isAvailable()) {
      throw new Error('OPENAI_API_KEY is not configured in server environment.');
    }

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.modelId,
        messages: [
          {
            role: 'system',
            content: 'You are an objective assessment integrity analyst. Write 2-3 concise sentences analyzing candidate telemetry.',
          },
          {
            role: 'user',
            content: JSON.stringify(request),
          },
        ],
        temperature: 0.2,
      }),
    });

    if (!response.ok) throw new Error(`OpenAI API returned ${response.status}: ${response.statusText}`);
    const data = await response.json();
    return data.choices?.[0]?.message?.content?.trim() || 'Analysis generated by OpenAI.';
  }

  async generateAllocationReasoning(request: AllocationExplanationRequest): Promise<string> {
    if (!this.isAvailable()) throw new Error('OPENAI_API_KEY is not configured.');

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${this.apiKey}`,
      },
      body: JSON.stringify({
        model: this.modelId,
        messages: [
          {
            role: 'system',
            content: 'Explain why candidate was matched to this company based on preferences and quota constraints.',
          },
          {
            role: 'user',
            content: JSON.stringify(request),
          },
        ],
        temperature: 0.2,
      }),
    });

    if (!response.ok) throw new Error(`OpenAI API returned ${response.status}`);
    const data = await response.json();
    return data.choices?.[0]?.message?.content?.trim() || 'Allocation verified by OpenAI.';
  }
}

// ─── 3. Behavioral Telemetry Scoring Engine (Deterministic Feature Extractor) ──
export class BehavioralTelemetryEngine {
  readonly version = 'telemetry-heuristics-v2.0';

  public computeBehavioralBreakdown(request: AnomalyAnalysisRequest) {
    const significantSignals = request.signals.filter((s) => s.riskContribution > 0);
    const totalPenalty = 100 - request.authenticityScore;

    let technicalHeuristics = '';
    const recommendedActions: string[] = [];

    if (significantSignals.length === 0) {
      technicalHeuristics = `Standard human typing cadence verified. Zero external clipboard injections detected, and candidate maintained continuous focus on the assessment tab without abnormal blur latency.`;
      recommendedActions.push('Session verified authentic. No manual intervention required.');
    } else {
      const parts: string[] = [];
      for (const s of significantSignals) {
        if (s.signal.includes('paste')) {
          parts.push(`${s.value} clipboard paste operations (Risk penalty: +${s.riskContribution} pts)`);
        } else if (s.signal.includes('blur')) {
          parts.push(`${s.value} window defocus events totaling ${s.value}s outside editor (Risk penalty: +${s.riskContribution} pts)`);
        } else if (s.signal.includes('insertion')) {
          parts.push(`Single injection of ${s.value} characters without typing flight time (Risk penalty: +${s.riskContribution} pts)`);
        }
      }

      technicalHeuristics = `Telemetry feature extraction flagged ${significantSignals.length} anomalous vector(s): ${parts.join('; ')}. Aggregate penalty: ${totalPenalty} pts.`;

      if (totalPenalty >= 70) {
        recommendedActions.push('High Priority: Review recorded keystroke flight times and code insertion timeline.');
        recommendedActions.push('Schedule a technical defense interview before confirming round completion.');
      } else if (totalPenalty >= 40) {
        recommendedActions.push('Manual Review: Compare submitted code against known external documentation.');
      } else {
        recommendedActions.push('Low Priority: Monitor subsequent recruitment rounds for recurring patterns.');
      }
    }

    return {
      authenticityScore: request.authenticityScore,
      riskLevel: request.riskLevel,
      contributingFactors: significantSignals.map((s) => `${s.description} (Weight: ${s.weight}x, Contribution: ${s.riskContribution} pts)`),
      technicalHeuristics,
      recommendedActions,
    };
  }

  public computeAllocationSummary(request: AllocationExplanationRequest) {
    const deterministicAllocationSummary = `Candidate ${request.studentName} (GPA: ${request.gpa.toFixed(2)}, Department: ${request.department}) was ranked #${request.studentRankForDrive} in ${request.assignedCompany}'s preference matrix. Under the Gale-Shapley deferred-acceptance algorithm with ${request.totalPositions} open position(s), candidate was matched without displacing any higher-priority applicant.`;

    const policyComplianceNotes = request.policyApplied
      ? `Compliant with Offer Policy "${request.policyApplied.name}" (Tier: ${request.assignedTier.toUpperCase()}). Student offer status locked against lower-tier offers while preserving merit-based upgrade eligibility.`
      : `Assignment satisfied standard institutional eligibility cutoffs and drive capacity.`;

    return {
      deterministicAllocationSummary,
      policyComplianceNotes,
    };
  }
}

// ─── 4. AIService Hub ──────────────────────────────────────────
export class AIService {
  private static instance: AIService;
  private behavioralEngine = new BehavioralTelemetryEngine();
  private providers: Map<string, IAIProvider> = new Map();
  private activeProviderKey: string;

  private constructor() {
    this.providers.set('gemini', new GeminiProvider());
    this.providers.set('openai', new OpenAIProvider());

    const envProvider = (process.env.AI_PROVIDER || '').toLowerCase();
    if (envProvider && this.providers.has(envProvider)) {
      this.activeProviderKey = envProvider;
    } else if (process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY) {
      this.activeProviderKey = 'gemini';
    } else if (process.env.OPENAI_API_KEY) {
      this.activeProviderKey = 'openai';
    } else {
      this.activeProviderKey = 'behavioral';
    }
  }

  public static getInstance(): AIService {
    if (!AIService.instance) {
      AIService.instance = new AIService();
    }
    return AIService.instance;
  }

  public getStatus(): {
    activeProvider: string;
    model: string;
    isGenerativeAIConfigured: boolean;
    behavioralEngineVersion: string;
    supportedProviders: string[];
  } {
    const provider = this.providers.get(this.activeProviderKey);
    return {
      activeProvider: provider ? provider.name : 'Behavioral Telemetry Engine',
      model: provider ? provider.modelId : this.behavioralEngine.version,
      isGenerativeAIConfigured: Boolean(provider && provider.isAvailable()),
      behavioralEngineVersion: this.behavioralEngine.version,
      supportedProviders: ['gemini', 'openai', 'behavioral'],
    };
  }

  public setProvider(providerKey: string): boolean {
    if (providerKey === 'behavioral' || this.providers.has(providerKey)) {
      this.activeProviderKey = providerKey;
      return true;
    }
    return false;
  }

  public async analyzeAssessmentTelemetry(request: AnomalyAnalysisRequest): Promise<AnomalyAnalysisResponse> {
    const behavioralBreakdown = this.behavioralEngine.computeBehavioralBreakdown(request);
    const provider = this.providers.get(this.activeProviderKey);

    let generativeExplanation: string | null = null;
    let isAIAvailable = false;

    if (provider && provider.isAvailable()) {
      try {
        generativeExplanation = await provider.generateAnomalyReasoning(request);
        isAIAvailable = true;
      } catch (err: any) {
        console.warn(`[AIService] Generative AI call to ${provider.name} failed:`, err.message);
        generativeExplanation = `Generative AI analysis unavailable (${err.message}).`;
        isAIAvailable = false;
      }
    } else if (provider) {
      generativeExplanation = `Generative AI Analysis Unavailable: API key not configured for ${provider.name}. Set GEMINI_API_KEY or OPENAI_API_KEY in server environment.`;
    }

    return {
      isAIAvailable,
      aiProvider: provider ? provider.name : null,
      aiModel: provider ? provider.modelId : null,
      timestamp: new Date().toISOString(),
      generativeExplanation,
      behavioralRiskBreakdown: behavioralBreakdown,
    };
  }

  public async analyzeAssessmentAnomaly(request: AnomalyAnalysisRequest): Promise<AnomalyAnalysisResponse> {
    return this.analyzeAssessmentTelemetry(request);
  }

  public async explainAllocationDecision(request: AllocationExplanationRequest): Promise<AllocationExplanationResponse> {
    const deterministic = this.behavioralEngine.computeAllocationSummary(request);
    const provider = this.providers.get(this.activeProviderKey);

    let generativeReasoning: string | null = null;
    let isAIAvailable = false;

    if (provider && provider.isAvailable()) {
      try {
        generativeReasoning = await provider.generateAllocationReasoning(request);
        isAIAvailable = true;
      } catch (err: any) {
        generativeReasoning = `Generative AI reasoning unavailable: ${err.message}`;
        isAIAvailable = false;
      }
    } else if (provider) {
      generativeReasoning = `Generative AI reasoning unavailable: API key not configured for ${provider.name}.`;
    }

    return {
      isAIAvailable,
      aiProvider: provider ? provider.name : null,
      aiModel: provider ? provider.modelId : null,
      timestamp: new Date().toISOString(),
      generativeReasoning,
      deterministicAllocationSummary: deterministic.deterministicAllocationSummary,
      policyComplianceNotes: deterministic.policyComplianceNotes,
    };
  }
}

export const aiService = AIService.getInstance();
